import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Footer from '@/components/shared/Footer'
import Navbar from '@/components/shared/Navbar'
import NextAuthProvider from './providers/NextAuthProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata = {
  title: 'Mission ISSB',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>

          <Navbar />

          {children}

          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  )
}
