// "use client"
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import NextAuthProvider from './providers/NextAuthProvider'
import LayoutWrapper from '@/components/LayoutWrapper'
import { Toaster } from 'react-hot-toast'
import QueryProvider from './providers/QueryProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata = {
  title: 'Mission ISSB',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
         <QueryProvider>

          <Toaster />
          
          <LayoutWrapper>{children}</LayoutWrapper>

        </NextAuthProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
